# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

WORKDIR /app

# Copy requirements and remove problematic logging package
COPY requirements.txt ./
RUN sed -i '/^logging/d' requirements.txt && \
    pip install --no-cache-dir -r requirements.txt

# Copy source files
COPY . .

CMD ["python", "pypi_server.py"]
